

import java.awt.Container;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.PreparedStatement;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author hanchaelyeong
 */

public class MainFrame extends javax.swing.JFrame {
    DB_MAN DBM =new DB_MAN();
    SignUp addMem = new SignUp();
    // 최소 8자, 최대 20자 상수 선언
    final int MIN = 8;
    final int MAX = 20;
    // 패스워드 상태정보 상수 선언
    final int NONE_PW = 0;
    final int PW_DIFF = 1;
    final int PW_SPACE = 2;
    final int PW_LEN = 3;
    final int PW_REX = 4;
    final int PW_REFT = 5;
    final int USE = 6;
    // 유효성 검사 결과 상수 선언
    final boolean VALID = true;
    final boolean INVALID = false;
    // 수정 Row 기억
    int iCntRow = 0;
    // 삭제 Row 기억
    int delete_row;
    
    private String login_id;
    
    public MainFrame() {
        initComponents();
       
        GridLayout grid = new GridLayout(2, 2);
        grid.setVgap(5);
        setSize(430,250);
        setVisible(true);
        
     }

    private void setPwText(int result){
        if(result == NONE_PW)
            txt2.setText("패스워드를 입력 해 주세요");
        else if(result == PW_DIFF)
            txt2.setText("패스워드가 서로 다릅니다");
        else if(result == PW_SPACE)
            txt2.setText("패스워드에 공백은 들어갈 수 없습니다");
        else if(result == PW_LEN)
            txt2.setText("패스워드의 길이는 8글자 이상 20글자 미만이어야 합니다");
        else if(result == PW_REX)
            txt2.setText("패스워드에는 최소 문자,숫자,특수문자가 한개이상 포함되어야 합니다");
        else if(result == PW_REFT)
            txt2.setText("패스워드에 동일한 문자를 3번이상 사용할 수 없습니다");
        else if(result == USE)
            txt2.setText("패스워드를 사용 가능합니다");
        else
            txt2.setText("오류");
    }
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        회원가입 = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        pw = new javax.swing.JLabel();
        tel = new javax.swing.JLabel();
        memID = new javax.swing.JTextField();
        name = new javax.swing.JLabel();
        memTEL = new javax.swing.JTextField();
        jB_checkID = new javax.swing.JButton();
        jB_memSave = new javax.swing.JButton();
        txt = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt2 = new javax.swing.JLabel();
        memPWCK = new javax.swing.JPasswordField();
        memPW = new javax.swing.JPasswordField();
        memNAME = new javax.swing.JTextField();
        도서_관리 = new javax.swing.JDialog();
        jB_search = new javax.swing.JButton();
        jTF_search = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jT_book_Mgr = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_Mgr = new javax.swing.JMenu();
        jMenu_add = new javax.swing.JMenuItem();
        jMenu_update = new javax.swing.JMenuItem();
        jMenu_delete = new javax.swing.JMenuItem();
        jMenu_exit = new javax.swing.JMenuItem();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        회원가입_완료 = new javax.swing.JDialog();
        jB_signUp_complete = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        로그인_실패 = new javax.swing.JDialog();
        jB_login_fail = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        도서추가 = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTF_bookID = new javax.swing.JTextField();
        jTF_bookName = new javax.swing.JTextField();
        jTF_bookPb = new javax.swing.JTextField();
        jTF_bookDate = new javax.swing.JTextField();
        jB_addBook = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        도서수정 = new javax.swing.JDialog();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTF_bookID_Update = new javax.swing.JTextField();
        jTF_bookName_Update = new javax.swing.JTextField();
        jTF_bookPb_Update = new javax.swing.JTextField();
        jTF_bookDate_Update = new javax.swing.JTextField();
        jB_updateBook = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        도서삭제_확인 = new javax.swing.JDialog();
        jB_delete_yes = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jB_delete_no = new javax.swing.JButton();
        도서_일반 = new javax.swing.JDialog();
        jB_search2 = new javax.swing.JButton();
        jTF_search1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jT_book_Genr = new javax.swing.JTable();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu_Genr = new javax.swing.JMenu();
        jMenu_rental = new javax.swing.JMenuItem();
        jMenu_return = new javax.swing.JMenuItem();
        jMenu_search = new javax.swing.JMenuItem();
        jMenu_exit1 = new javax.swing.JMenuItem();
        도서_반납 = new javax.swing.JDialog();
        jB_return = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jT_book_return = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jF_ID = new javax.swing.JTextField();
        jB_signUp = new javax.swing.JButton();
        jB_signIn = new javax.swing.JButton();
        jPF_pwd = new javax.swing.JPasswordField();

        회원가입.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        회원가입.setBounds(new java.awt.Rectangle(0, 25, 500, 500));
        회원가입.setMinimumSize(new java.awt.Dimension(500, 302));
        회원가입.setModal(true);
        회원가입.setSize(new java.awt.Dimension(400, 400));
        java.awt.GridBagLayout 회원가입Layout = new java.awt.GridBagLayout();
        회원가입Layout.columnWidths = new int[] {0, 25, 0, 25, 0, 25, 0, 25, 0};
        회원가입Layout.rowHeights = new int[] {0, 8, 0, 8, 0, 8, 0, 8, 0, 8, 0, 8, 0, 8, 0, 8, 0, 8, 0, 8, 0, 8, 0, 8, 0, 8, 0};
        회원가입Layout.columnWeights = new double[] {10.0};
        회원가입Layout.rowWeights = new double[] {10.1};
        회원가입.getContentPane().setLayout(회원가입Layout);

        jLabel4.setText("회 원 가 입");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        회원가입.getContentPane().add(jLabel4, gridBagConstraints);

        id.setText("ID");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        회원가입.getContentPane().add(id, gridBagConstraints);

        pw.setText("PW");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        회원가입.getContentPane().add(pw, gridBagConstraints);

        tel.setText("휴대전화");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 16;
        회원가입.getContentPane().add(tel, gridBagConstraints);

        memID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                memIDFocusLost(evt);
            }
        });
        memID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                memIDKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 150;
        회원가입.getContentPane().add(memID, gridBagConstraints);

        name.setText("이름");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 20;
        회원가입.getContentPane().add(name, gridBagConstraints);

        memTEL.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                memTELFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.ipadx = 150;
        회원가입.getContentPane().add(memTEL, gridBagConstraints);

        jB_checkID.setText("중복검사");
        jB_checkID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_checkIDActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        회원가입.getContentPane().add(jB_checkID, gridBagConstraints);

        jB_memSave.setText("회원가입");
        jB_memSave.setToolTipText("");
        jB_memSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_memSaveActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 24;
        회원가입.getContentPane().add(jB_memSave, gridBagConstraints);

        txt.setToolTipText("");
        txt.setVerifyInputWhenFocusTarget(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 170;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        회원가입.getContentPane().add(txt, gridBagConstraints);

        jLabel5.setText("PW확인");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        회원가입.getContentPane().add(jLabel5, gridBagConstraints);

        txt2.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        txt2.setText("패스워드를 입력 해 주세요");
        txt2.setMaximumSize(new java.awt.Dimension(170, 17));
        txt2.setMinimumSize(new java.awt.Dimension(170, 17));
        txt2.setPreferredSize(new java.awt.Dimension(170, 17));
        txt2.setVerifyInputWhenFocusTarget(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        회원가입.getContentPane().add(txt2, gridBagConstraints);

        memPWCK.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                memPWCKFocusLost(evt);
            }
        });
        memPWCK.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                memPWCKKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.ipadx = 150;
        회원가입.getContentPane().add(memPWCK, gridBagConstraints);

        memPW.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                memPWFocusLost(evt);
            }
        });
        memPW.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                memPWKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 150;
        회원가입.getContentPane().add(memPW, gridBagConstraints);

        memNAME.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                memNAMEFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.ipadx = 150;
        회원가입.getContentPane().add(memNAME, gridBagConstraints);

        도서_관리.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        도서_관리.setSize(new java.awt.Dimension(422, 360));
        도서_관리.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                도서_관리WindowActivated(evt);
            }
        });

        jB_search.setText("검색");
        jB_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_searchActionPerformed(evt);
            }
        });

        jT_book_Mgr.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "도서ID", "도서이름", "출판사", "등록일"
            }
        ));
        jT_book_Mgr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jT_book_MgrMouseClicked(evt);
            }
        });
        jT_book_Mgr.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jT_book_MgrPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(jT_book_Mgr);
        if (jT_book_Mgr.getColumnModel().getColumnCount() > 0) {
            jT_book_Mgr.getColumnModel().getColumn(3).setHeaderValue("등록일");
        }

        jMenu_Mgr.setLabel("관리");

        jMenu_add.setText("추가");
        jMenu_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_addActionPerformed(evt);
            }
        });
        jMenu_Mgr.add(jMenu_add);

        jMenu_update.setText("수정");
        jMenu_update.setEnabled(false);
        jMenu_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_updateActionPerformed(evt);
            }
        });
        jMenu_Mgr.add(jMenu_update);

        jMenu_delete.setText("삭제");
        jMenu_delete.setEnabled(false);
        jMenu_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_deleteActionPerformed(evt);
            }
        });
        jMenu_Mgr.add(jMenu_delete);

        jMenu_exit.setText("종료");
        jMenu_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_exitActionPerformed(evt);
            }
        });
        jMenu_Mgr.add(jMenu_exit);

        jMenuBar1.add(jMenu_Mgr);

        도서_관리.setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout 도서_관리Layout = new javax.swing.GroupLayout(도서_관리.getContentPane());
        도서_관리.getContentPane().setLayout(도서_관리Layout);
        도서_관리Layout.setHorizontalGroup(
            도서_관리Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(도서_관리Layout.createSequentialGroup()
                .addGroup(도서_관리Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(도서_관리Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(도서_관리Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jTF_search, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jB_search)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        도서_관리Layout.setVerticalGroup(
            도서_관리Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(도서_관리Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(도서_관리Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTF_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_search))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        회원가입_완료.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        회원가입_완료.setTitle("회원가입 완료!");
        회원가입_완료.setSize(new java.awt.Dimension(325, 130));

        jB_signUp_complete.setText("OK");
        jB_signUp_complete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_signUp_completeActionPerformed(evt);
            }
        });

        jLabel6.setText("회원가입이 완료되었습니다!");

        javax.swing.GroupLayout 회원가입_완료Layout = new javax.swing.GroupLayout(회원가입_완료.getContentPane());
        회원가입_완료.getContentPane().setLayout(회원가입_완료Layout);
        회원가입_완료Layout.setHorizontalGroup(
            회원가입_완료Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(회원가입_완료Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jB_signUp_complete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, 회원가입_완료Layout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(89, 89, 89))
        );
        회원가입_완료Layout.setVerticalGroup(
            회원가입_완료Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, 회원가입_완료Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jB_signUp_complete, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        로그인_실패.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        로그인_실패.setTitle("로그인_실패");

        jB_login_fail.setText("OK");
        jB_login_fail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_login_failActionPerformed(evt);
            }
        });

        jLabel7.setText("계정정보를 확인 해 주시기 바랍니다.");

        javax.swing.GroupLayout 로그인_실패Layout = new javax.swing.GroupLayout(로그인_실패.getContentPane());
        로그인_실패.getContentPane().setLayout(로그인_실패Layout);
        로그인_실패Layout.setHorizontalGroup(
            로그인_실패Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(로그인_실패Layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jB_login_fail)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, 로그인_실패Layout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(85, 85, 85))
        );
        로그인_실패Layout.setVerticalGroup(
            로그인_실패Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, 로그인_실패Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jB_login_fail, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        도서추가.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        도서추가.setSize(new java.awt.Dimension(400, 300));
        java.awt.GridBagLayout 도서추가Layout = new java.awt.GridBagLayout();
        도서추가Layout.columnWidths = new int[] {0, 26, 0, 26, 0, 26, 0, 26, 0, 26, 0, 26, 0, 26, 0, 26, 0};
        도서추가Layout.rowHeights = new int[] {0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0, 9, 0};
        도서추가.getContentPane().setLayout(도서추가Layout);

        jLabel8.setText("도서ID");
        jLabel8.setToolTipText("");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        도서추가.getContentPane().add(jLabel8, gridBagConstraints);

        jLabel9.setText("도서이름");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 10;
        도서추가.getContentPane().add(jLabel9, gridBagConstraints);

        jLabel10.setText("출판사");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 14;
        도서추가.getContentPane().add(jLabel10, gridBagConstraints);

        jLabel11.setText("등록일");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 18;
        도서추가.getContentPane().add(jLabel11, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 150;
        도서추가.getContentPane().add(jTF_bookID, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.ipadx = 150;
        도서추가.getContentPane().add(jTF_bookName, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.ipadx = 150;
        도서추가.getContentPane().add(jTF_bookPb, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.ipadx = 150;
        도서추가.getContentPane().add(jTF_bookDate, gridBagConstraints);

        jB_addBook.setText("등록");
        jB_addBook.setToolTipText("");
        jB_addBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_addBookActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 22;
        도서추가.getContentPane().add(jB_addBook, gridBagConstraints);

        jLabel12.setText("도서 추가 ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        도서추가.getContentPane().add(jLabel12, gridBagConstraints);

        도서수정.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        도서수정.setSize(new java.awt.Dimension(400, 300));
        도서수정.getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel18.setText("도서ID");
        jLabel18.setToolTipText("");
        jLabel18.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        도서수정.getContentPane().add(jLabel18, gridBagConstraints);

        jLabel19.setText("도서이름");
        jLabel19.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 10;
        도서수정.getContentPane().add(jLabel19, gridBagConstraints);

        jLabel20.setText("출판사");
        jLabel20.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 14;
        도서수정.getContentPane().add(jLabel20, gridBagConstraints);

        jLabel21.setText("등록일");
        jLabel21.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 18;
        도서수정.getContentPane().add(jLabel21, gridBagConstraints);

        jTF_bookID_Update.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 150;
        도서수정.getContentPane().add(jTF_bookID_Update, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.ipadx = 150;
        도서수정.getContentPane().add(jTF_bookName_Update, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.ipadx = 150;
        도서수정.getContentPane().add(jTF_bookPb_Update, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.ipadx = 150;
        도서수정.getContentPane().add(jTF_bookDate_Update, gridBagConstraints);

        jB_updateBook.setText("수정");
        jB_updateBook.setToolTipText("");
        jB_updateBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_updateBookActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 22;
        도서수정.getContentPane().add(jB_updateBook, gridBagConstraints);

        jLabel22.setText("도서 수정");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        도서수정.getContentPane().add(jLabel22, gridBagConstraints);

        도서삭제_확인.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        도서삭제_확인.setTitle("회원가입 완료!");
        도서삭제_확인.setSize(new java.awt.Dimension(325, 130));

        jB_delete_yes.setText("Yes");
        jB_delete_yes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_delete_yesActionPerformed(evt);
            }
        });

        jLabel13.setText("정말 삭제하시겠습니까?");

        jB_delete_no.setText("No");
        jB_delete_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_delete_noActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout 도서삭제_확인Layout = new javax.swing.GroupLayout(도서삭제_확인.getContentPane());
        도서삭제_확인.getContentPane().setLayout(도서삭제_확인Layout);
        도서삭제_확인Layout.setHorizontalGroup(
            도서삭제_확인Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(도서삭제_확인Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jB_delete_yes)
                .addGap(37, 37, 37)
                .addComponent(jB_delete_no)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, 도서삭제_확인Layout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(89, 89, 89))
        );
        도서삭제_확인Layout.setVerticalGroup(
            도서삭제_확인Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, 도서삭제_확인Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(도서삭제_확인Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_delete_yes, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_delete_no, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        도서_일반.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        도서_일반.setSize(new java.awt.Dimension(422, 360));
        도서_일반.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                도서_일반WindowActivated(evt);
            }
        });

        jB_search2.setText("검색");
        jB_search2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_search2ActionPerformed(evt);
            }
        });

        jT_book_Genr.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "도서ID", "도서이름", "출판사", "등록일", "대여"
            }
        ));
        jT_book_Genr.getTableHeader().setReorderingAllowed(false);
        jT_book_Genr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jT_book_GenrMouseClicked(evt);
            }
        });
        jT_book_Genr.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jT_book_GenrPropertyChange(evt);
            }
        });
        jScrollPane2.setViewportView(jT_book_Genr);
        if (jT_book_Genr.getColumnModel().getColumnCount() > 0) {
            jT_book_Genr.getColumnModel().getColumn(3).setHeaderValue("등록일");
        }

        jMenu_Genr.setText("도서");

        jMenu_rental.setText("대여");
        jMenu_rental.setEnabled(false);
        jMenu_rental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_rentalActionPerformed(evt);
            }
        });
        jMenu_Genr.add(jMenu_rental);

        jMenu_return.setText("반납");
        jMenu_return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_returnActionPerformed(evt);
            }
        });
        jMenu_Genr.add(jMenu_return);

        jMenu_search.setText("조회");
        jMenu_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_searchActionPerformed(evt);
            }
        });
        jMenu_Genr.add(jMenu_search);

        jMenu_exit1.setText("종료");
        jMenu_exit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_exit1ActionPerformed(evt);
            }
        });
        jMenu_Genr.add(jMenu_exit1);

        jMenuBar2.add(jMenu_Genr);

        도서_일반.setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout 도서_일반Layout = new javax.swing.GroupLayout(도서_일반.getContentPane());
        도서_일반.getContentPane().setLayout(도서_일반Layout);
        도서_일반Layout.setHorizontalGroup(
            도서_일반Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(도서_일반Layout.createSequentialGroup()
                .addGroup(도서_일반Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(도서_일반Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(도서_일반Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jTF_search1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jB_search2)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        도서_일반Layout.setVerticalGroup(
            도서_일반Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(도서_일반Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(도서_일반Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTF_search1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_search2))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        도서_반납.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        도서_반납.setBounds(new java.awt.Rectangle(0, 25, 450, 320));
        도서_반납.setSize(new java.awt.Dimension(450, 320));
        도서_반납.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                도서_반납WindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                도서_반납WindowClosed(evt);
            }
        });

        jB_return.setText("반납");
        jB_return.setEnabled(false);
        jB_return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_returnActionPerformed(evt);
            }
        });

        jT_book_return.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "대여번호", "회원번호", "도서ID", "도서이름", "대여일"
            }
        ));
        jT_book_return.getTableHeader().setReorderingAllowed(false);
        jT_book_return.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jT_book_returnMouseClicked(evt);
            }
        });
        jT_book_return.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jT_book_returnPropertyChange(evt);
            }
        });
        jScrollPane3.setViewportView(jT_book_return);

        javax.swing.GroupLayout 도서_반납Layout = new javax.swing.GroupLayout(도서_반납.getContentPane());
        도서_반납.getContentPane().setLayout(도서_반납Layout);
        도서_반납Layout.setHorizontalGroup(
            도서_반납Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(도서_반납Layout.createSequentialGroup()
                .addGroup(도서_반납Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(도서_반납Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(도서_반납Layout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(jB_return)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        도서_반납Layout.setVerticalGroup(
            도서_반납Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(도서_반납Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jB_return)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("도서 관리 프로그램 ");

        jLabel2.setText("아이디");

        jLabel3.setText("비밀번호");

        jF_ID.setToolTipText("");
        jF_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jF_IDActionPerformed(evt);
            }
        });

        jB_signUp.setText("회원가입");
        jB_signUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_signUpActionPerformed(evt);
            }
        });

        jB_signIn.setText("로그인");
        jB_signIn.setActionCommand("");
        jB_signIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_signInActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(159, 159, 159))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jF_ID, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                            .addComponent(jPF_pwd))
                        .addGap(109, 109, 109))))
            .addGroup(layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jB_signIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jB_signUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jF_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jPF_pwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jB_signIn)
                .addGap(18, 18, 18)
                .addComponent(jB_signUp)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_signUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_signUpActionPerformed
        // TODO add your handling code here:
       
        
       회원가입.setLocation(300,300);
       회원가입.setSize(400, 350);
       회원가입.show();
                
    }//GEN-LAST:event_jB_signUpActionPerformed

    private void jB_memSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_memSaveActionPerformed
        // TODO add your handling code here:
        
        
//        String userid = memID.getText();
//        String pw = memPW.getText();
//        String pwck = memPWCK.getText();
//        String tel = memTEL.getText();
//        String name = memNAME.getText();
        
        
        
        
      
        
        
        String strSQL = "insert into member(userid,pw,tel,name) "
        +"values('" +addMem.userid+ "','" +addMem.pw+"','"+addMem.tel+"','"+addMem.name+"')";       
        System.out.println(strSQL);

        try{

            DBM.dbOpen();
            DBM.DB_stmt.executeUpdate(strSQL);  
            DBM.dbClose();
            회원가입.dispose();
            회원가입_완료.setLocation(300,300);
            회원가입_완료.show();

        }catch(Exception e){
            System.out.println("SQLException"+e.getMessage());
        }
        
        
        
        
        
    }//GEN-LAST:event_jB_memSaveActionPerformed

    private void jB_checkIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_checkIDActionPerformed
        // TODO add your handling code here:
        addMem.userid = memID.getText();

        String strSQL = "select userid from member where userid='" + addMem.userid +"'";
        System.out.println(strSQL);

        try{
            DBM.dbOpen();
            var rs = DBM.DB_stmt.executeQuery(strSQL);
            
            if(rs.next()){
                if(addMem.userid.equals(rs.getString("userid"))){
                    txt.setText("아이디 중복");
                    addMem.id_valid=INVALID;
                }
                          
            }else{
                txt.setText("아이디 가능");
                addMem.id_valid=VALID;
                jB_checkID.setEnabled(false);
            }
            
            DBM.dbClose();
            

        }catch(Exception e){
             System.out.println("SQLException"+e.getMessage());
        }
    }//GEN-LAST:event_jB_checkIDActionPerformed

    private void memPWCKFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_memPWCKFocusLost
        // TODO add your handling code here:
        addMem.pwck = memPWCK.getText();
        setPwText(addMem.isValidPassword());
        jB_memSave.setEnabled(addMem.ableCheck()); 
    }//GEN-LAST:event_memPWCKFocusLost

    private void memPWFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_memPWFocusLost
        // TODO add your handling code here:
        addMem.pw = memPW.getText();
        setPwText(addMem.isValidPassword());
        jB_memSave.setEnabled(addMem.ableCheck()); 
    }//GEN-LAST:event_memPWFocusLost

    private void jF_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jF_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jF_IDActionPerformed

    private void memTELFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_memTELFocusLost
        // TODO add your handling code here:
        addMem.tel = memTEL.getText();
        jB_memSave.setEnabled(addMem.ableCheck()); 
    }//GEN-LAST:event_memTELFocusLost

    private void memIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_memIDKeyPressed
        // TODO add your handling code here:
        addMem.id_valid=INVALID;
        jB_checkID.setEnabled(true);
        jB_memSave.setEnabled(false);
    }//GEN-LAST:event_memIDKeyPressed

    private void memIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_memIDFocusLost
        // TODO add your handling code here:
        addMem.userid = memID.getText();
        jB_memSave.setEnabled(addMem.ableCheck()); 
    }//GEN-LAST:event_memIDFocusLost

    private void memNAMEFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_memNAMEFocusLost
        // TODO add your handling code here:
        addMem.name = memNAME.getText();
        jB_memSave.setEnabled(addMem.ableCheck()); 
    }//GEN-LAST:event_memNAMEFocusLost

    private void memPWCKKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_memPWCKKeyPressed
        // TODO add your handling code here:
        addMem.pw_valid=INVALID;
    }//GEN-LAST:event_memPWCKKeyPressed

    private void memPWKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_memPWKeyPressed
        // TODO add your handling code here:
        addMem.pw_valid=INVALID;
    }//GEN-LAST:event_memPWKeyPressed

    private void jB_signUp_completeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_signUp_completeActionPerformed
        // TODO add your handling code here:
        회원가입_완료.dispose();
    }//GEN-LAST:event_jB_signUp_completeActionPerformed

    private void jB_signInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_signInActionPerformed
        // TODO add your handling code here:
        String userId = jF_ID.getText();
        String userPw = jPF_pwd.getText();
        System.out.println(userPw);
        String strSQL = "select id,userid,pw from member where userid='" + userId +"'";
        
        System.out.println(strSQL);

        try{
            DBM.dbOpen();
            var rs = DBM.DB_stmt.executeQuery(strSQL);
            if(rs.next()){
                if(userId.equals(rs.getString("userid"))&&userPw.equals(rs.getString("pw"))){
                    login_id = rs.getString("id");
                    if(userId.equals("cofud") || userId.equals("admin"))
                    {
                        도서_관리.setLocation(300, 300);
                        도서_관리.setSize(430, 430);
                        도서_관리.show();
                        re_rendering(true);
                    }
                    else
                    {
                        도서_일반.setLocation(300, 300);
                        도서_일반.setSize(430, 430);
                        도서_일반.show();
                        re_rendering(false);
                        
                    }
                    dispose();
                }
                          
            }else{
                로그인_실패.setLocation(300,300);
                로그인_실패.show();
            }
            DBM.dbClose();
            

        }catch(Exception e){
             System.out.println("SQLException"+e.getMessage());
        }
        
    }//GEN-LAST:event_jB_signInActionPerformed
    private void re_rendering(boolean permission){
        String strSQL = "select * from book";
        DefaultTableModel dTable;
        int count=0;
        try{
            DBM.DB_rs = DBM.DB_stmt.executeQuery(strSQL);
            if(permission == true)
            {
                dTable = (DefaultTableModel)jT_book_Mgr.getModel();
                dTable.setNumRows(0);
                while(DBM.DB_rs.next()){
                    dTable.insertRow(count,new Object[]{DBM.DB_rs.getInt("book_id"),DBM.DB_rs.getString("book_name"),DBM.DB_rs.getString("book_pb"),DBM.DB_rs.getString("book_date")});
                    count+=1;
                }
                jT_book_Mgr.updateUI();
            }
            else
            {
                dTable = (DefaultTableModel)jT_book_Genr.getModel();
                dTable.setNumRows(0);
                String rental_able;
                DBM.sub_dbOpen();
                while(DBM.DB_rs.next()){
                    strSQL="select * from sys.book_rental where book_id="+DBM.DB_rs.getString("book_id")+" and rental_date is not null and return_date is null";
                    DBM.DB_sub_rs = DBM.DB_sub_stmt.executeQuery(strSQL);
                    System.out.println(strSQL);
                    if(DBM.DB_sub_rs.next()){
                        System.out.println("대여가능");
                        rental_able = "불가능";
                    }
                    else{
                        System.out.println("대여불가능");
                        rental_able="가능";
                    }
                    dTable.insertRow(count,new Object[]{DBM.DB_rs.getInt("book_id"),DBM.DB_rs.getString("book_name"),DBM.DB_rs.getString("book_pb"),DBM.DB_rs.getString("book_date"),rental_able});
                    count+=1;
                            
                }
                DBM.sub_dbClose();
                jT_book_Genr.updateUI();
            }
        }catch(Exception e){
             System.out.println("SQLException"+e.getMessage());
        }
    }
    private void jB_login_failActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_login_failActionPerformed
        // TODO add your handling code here:
        로그인_실패.dispose();
    }//GEN-LAST:event_jB_login_failActionPerformed

    private void jMenu_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_addActionPerformed
        // TODO add your handling code here:
        도서추가.setLocation(300,300);
        도서추가.setSize(350,350);
        도서추가.show();
    }//GEN-LAST:event_jMenu_addActionPerformed

    private void 도서_관리WindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_도서_관리WindowActivated
        // TODO add your handling code here:

    }//GEN-LAST:event_도서_관리WindowActivated

    private void jB_addBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_addBookActionPerformed
        // TODO add your handling code here:
        String strSQL = "insert into book "
        +"values(" +jTF_bookID.getText()+ ",'" +jTF_bookName.getText()+"','"+jTF_bookPb.getText()+"','"+jTF_bookDate.getText()+"')";       
        System.out.println(strSQL);

        try{
            if(jTF_bookID.getText().equals("")||jTF_bookName.getText().equals("")||jTF_bookPb.getText().equals("")||jTF_bookDate.getText().equals(""))
                System.out.println("빈칸이 존재 합니다");
            else{
                DBM.dbOpen();
                DBM.DB_stmt.executeUpdate(strSQL);  
                re_rendering(true);
                DBM.dbClose();
                도서추가.dispose();
            }
            jTF_bookID.setText("");
            jTF_bookName.setText("");
            jTF_bookPb.setText("");
            jTF_bookDate.setText("");
        }catch(Exception e){
            System.out.println("SQLException"+e.getMessage());
        }
        
        
     
    }//GEN-LAST:event_jB_addBookActionPerformed

    private void jT_book_MgrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jT_book_MgrMouseClicked
        // TODO add your handling code here:
        System.out.println(jT_book_Mgr.getValueAt(jT_book_Mgr.getSelectedRow(),0));
        if(jT_book_Mgr.getValueAt(jT_book_Mgr.getSelectedRow(),0)==null){
            jMenu_update.setEnabled(false);
            jMenu_delete.setEnabled(false);
        }
        else{
            jMenu_update.setEnabled(true);
            jMenu_delete.setEnabled(true);
        }
        
    }//GEN-LAST:event_jT_book_MgrMouseClicked
    private void search_book(){
        String strSQL;
        if(jTF_search.getText().equals("")){
            strSQL = "select * from book";
        }else{
            strSQL = "select * from book where book_name like '%"+jTF_search.getText()+"%'";
            System.out.println(strSQL);
        }
        DefaultTableModel dTable = (DefaultTableModel)jT_book_Mgr.getModel();
        int count=0;
        System.out.println("찾기시작");
                
        try{
            DBM.dbOpen();
            var rs = DBM.DB_stmt.executeQuery(strSQL);
            dTable.setNumRows(0);
            System.out.println("여기는 오나?");
            while(rs.next()){
                dTable.insertRow(count,new Object[]{rs.getInt("book_id"),rs.getString("book_name"),rs.getString("book_pb"),rs.getString("book_date")});
                count+=1;
            }
            System.out.println("고럼 여기능?");
            jT_book_Mgr.updateUI();
        }catch(Exception e){
            System.out.println("SQLException"+e.getMessage());
        }
    }
    private void jB_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_searchActionPerformed
        // TODO add your handling code here:
        search_book();
    }//GEN-LAST:event_jB_searchActionPerformed

    private void jMenu_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_updateActionPerformed
        // TODO add your handling code here:
        
        iCntRow = jT_book_Mgr.getSelectedRow();
        
        jTF_bookID_Update.setText(jT_book_Mgr.getValueAt(iCntRow, 0).toString());
        jTF_bookName_Update.setText(jT_book_Mgr.getValueAt(iCntRow, 1).toString());
        jTF_bookPb_Update.setText(jT_book_Mgr.getValueAt(iCntRow, 2).toString());
        jTF_bookDate_Update.setText(jT_book_Mgr.getValueAt(iCntRow, 3).toString());
        도서수정.setLocation(300,300);
        도서수정.setSize(350,350);
        도서수정.show();
        
        
        
        
    }//GEN-LAST:event_jMenu_updateActionPerformed

    private void jB_updateBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_updateBookActionPerformed
        // TODO add your handling code here:
        String strSQL = "UPDATE sys.book SET book_name = '"+jTF_bookName_Update.getText()
                +"' , book_pb = '"+jTF_bookPb_Update.getText()+"' , book_date = '"+jTF_bookDate_Update.getText()+"' WHERE (book_id = "+jTF_bookID_Update.getText()+")";
        System.out.println(strSQL);
        try{
            DBM.dbOpen();
            DBM.DB_stmt.executeUpdate(strSQL);
            DBM.dbClose();
            jT_book_Mgr.setValueAt(jTF_bookName_Update.getText(), iCntRow, 1);
            jT_book_Mgr.setValueAt(jTF_bookPb_Update.getText(), iCntRow, 2);
            jT_book_Mgr.setValueAt(jTF_bookDate_Update.getText(), iCntRow, 3);
            jT_book_Mgr.updateUI();
            도서수정.dispose();
            
        }catch(Exception e){
            System.out.println("SQLException"+e.getMessage());
        }
    }//GEN-LAST:event_jB_updateBookActionPerformed

    private void jMenu_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_deleteActionPerformed
        // TODO add your handling code here:
        delete_row = jT_book_Mgr.getSelectedRow();
        도서삭제_확인.setLocation(300,300);
        도서삭제_확인.show();
    }//GEN-LAST:event_jMenu_deleteActionPerformed

    private void jB_delete_yesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_delete_yesActionPerformed
        // TODO add your handling code here:
        String strSQL = "DELETE FROM book WHERE (book_id = "+jT_book_Mgr.getValueAt(delete_row,0).toString()+")";
        System.out.println(strSQL);
        DefaultTableModel dTable = (DefaultTableModel)jT_book_Mgr.getModel();
        try{
            DBM.dbOpen();
            DBM.DB_stmt.executeUpdate(strSQL);
            DBM.dbClose();
            dTable.removeRow(delete_row);
            jT_book_Mgr.updateUI();
            도서삭제_확인.dispose();

            
        }catch(Exception e){
            System.out.println("SQLException"+e.getMessage());
        }
    }//GEN-LAST:event_jB_delete_yesActionPerformed

    private void jB_delete_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_delete_noActionPerformed
        // TODO add your handling code here:
        도서삭제_확인.dispose();
    }//GEN-LAST:event_jB_delete_noActionPerformed

    private void jT_book_MgrPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jT_book_MgrPropertyChange
        // TODO add your handling code here:
        jMenu_update.setEnabled(false);
        jMenu_delete.setEnabled(false);
    }//GEN-LAST:event_jT_book_MgrPropertyChange

    private void jB_search2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_search2ActionPerformed
        // TODO add your handling code here:
        search_book();
    }//GEN-LAST:event_jB_search2ActionPerformed

    private void jT_book_GenrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jT_book_GenrMouseClicked
        // TODO add your handling code here:
        System.out.println(jT_book_Genr.getValueAt(jT_book_Genr.getSelectedRow(),4));
        if(jT_book_Genr.getValueAt(jT_book_Genr.getSelectedRow(),4)=="불가능"){
            jMenu_rental.setEnabled(false);
        }
        else{
            jMenu_rental.setEnabled(true);
            
        }
    }//GEN-LAST:event_jT_book_GenrMouseClicked

    private void jT_book_GenrPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jT_book_GenrPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_book_GenrPropertyChange

    private void jMenu_rentalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_rentalActionPerformed
        // TODO add your handling code here:
        try{
            String strSQL;
            DBM.dbOpen();
            strSQL = "insert into sys.book_rental (mem_id, book_id) "
                +"values (" +login_id+ "," +jT_book_Genr.getValueAt(jT_book_Genr.getSelectedRow(),0)+")";       
            System.out.println(strSQL);
            DBM.DB_stmt.executeUpdate(strSQL);
            re_rendering(false);
            DBM.dbClose();
            jMenu_rental.setEnabled(false);
            
        } catch(Exception e){
            System.out.println("SQLException"+e.getMessage());
        }
        
    }//GEN-LAST:event_jMenu_rentalActionPerformed

    private void jMenu_returnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_returnActionPerformed
        // TODO add your handling code here:
        도서_일반.setVisible(false);

        try{
            int count=0;
            String strSQL;
            DefaultTableModel dTable = (DefaultTableModel)jT_book_return.getModel();
            dTable.setRowCount(0);
            DBM.dbOpen();
            DBM.sub_dbOpen();
            strSQL = "select * from book_rental where mem_id="+login_id+" and rental_date is not null and return_date is null";   
            System.out.println(strSQL);
            DBM.DB_rs = DBM.DB_stmt.executeQuery(strSQL);
            while(DBM.DB_rs.next()){
                DBM.DB_sub_rs = DBM.DB_sub_stmt.executeQuery("select book_name from book where book_id="+DBM.DB_rs.getInt("book_id"));
                if(DBM.DB_sub_rs.next())
                    dTable.insertRow(count,new Object[]{DBM.DB_rs.getInt("rental_number"),DBM.DB_rs.getInt("mem_id"),DBM.DB_rs.getInt("book_id"),DBM.DB_sub_rs.getString("book_name"),DBM.DB_rs.getString("rental_date")});
                count+=1;
            }
            jT_book_return.updateUI();
            DBM.sub_dbClose();
            DBM.dbClose();
            
        } catch(Exception e){
            System.out.println("SQLException"+e.getMessage());
        }
        도서_반납.setLocation(300,300);
        도서_반납.show();
    }//GEN-LAST:event_jMenu_returnActionPerformed

    private void jMenu_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu_searchActionPerformed

    private void 도서_일반WindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_도서_일반WindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_도서_일반WindowActivated

    private void jMenu_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_exitActionPerformed
        // TODO add your handling code here:
        System.exit(1);
    }//GEN-LAST:event_jMenu_exitActionPerformed

    private void jMenu_exit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_exit1ActionPerformed
        // TODO add your handling code here:
        System.exit(1);
    }//GEN-LAST:event_jMenu_exit1ActionPerformed

    private void jB_returnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_returnActionPerformed
        // TODO add your handling code here:
        String strSQL = "UPDATE sys.book_rental SET return_date = now() "
            +"WHERE (rental_number = "+jT_book_return.getValueAt(jT_book_return.getSelectedRow(),0)+")";
        System.out.println(strSQL);
        try{
            DBM.dbOpen();
            DBM.DB_stmt.executeUpdate(strSQL);
            re_rendering(false);
            DBM.dbClose();
            도서_반납.dispose();
            도서_일반.setVisible(true);
        } catch(Exception e){
            System.out.println("SQLException"+e.getMessage());
        }
    }//GEN-LAST:event_jB_returnActionPerformed

    private void jT_book_returnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jT_book_returnMouseClicked
        // TODO add your handling code here:
        jB_return.setEnabled(true);
    }//GEN-LAST:event_jT_book_returnMouseClicked

    private void jT_book_returnPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jT_book_returnPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_book_returnPropertyChange

    private void 도서_반납WindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_도서_반납WindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_도서_반납WindowActivated

    private void 도서_반납WindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_도서_반납WindowClosed
        // TODO add your handling code here:
        도서_일반.setVisible(true);
    }//GEN-LAST:event_도서_반납WindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.JLabel id;
    private javax.swing.JButton jB_addBook;
    private javax.swing.JButton jB_checkID;
    private javax.swing.JButton jB_delete_no;
    private javax.swing.JButton jB_delete_yes;
    private javax.swing.JButton jB_login_fail;
    private javax.swing.JButton jB_memSave;
    private javax.swing.JButton jB_return;
    private javax.swing.JButton jB_search;
    private javax.swing.JButton jB_search2;
    private javax.swing.JButton jB_signIn;
    private javax.swing.JButton jB_signUp;
    private javax.swing.JButton jB_signUp_complete;
    private javax.swing.JButton jB_updateBook;
    private javax.swing.JTextField jF_ID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu jMenu_Genr;
    private javax.swing.JMenu jMenu_Mgr;
    private javax.swing.JMenuItem jMenu_add;
    private javax.swing.JMenuItem jMenu_delete;
    private javax.swing.JMenuItem jMenu_exit;
    private javax.swing.JMenuItem jMenu_exit1;
    private javax.swing.JMenuItem jMenu_rental;
    private javax.swing.JMenuItem jMenu_return;
    private javax.swing.JMenuItem jMenu_search;
    private javax.swing.JMenuItem jMenu_update;
    private javax.swing.JPasswordField jPF_pwd;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTF_bookDate;
    private javax.swing.JTextField jTF_bookDate_Update;
    private javax.swing.JTextField jTF_bookID;
    private javax.swing.JTextField jTF_bookID_Update;
    private javax.swing.JTextField jTF_bookName;
    private javax.swing.JTextField jTF_bookName_Update;
    private javax.swing.JTextField jTF_bookPb;
    private javax.swing.JTextField jTF_bookPb_Update;
    private javax.swing.JTextField jTF_search;
    private javax.swing.JTextField jTF_search1;
    private javax.swing.JTable jT_book_Genr;
    private javax.swing.JTable jT_book_Mgr;
    private javax.swing.JTable jT_book_return;
    private javax.swing.JTextField memID;
    private javax.swing.JTextField memNAME;
    private javax.swing.JPasswordField memPW;
    private javax.swing.JPasswordField memPWCK;
    private javax.swing.JTextField memTEL;
    private javax.swing.JLabel name;
    private javax.swing.JLabel pw;
    private javax.swing.JLabel tel;
    private javax.swing.JLabel txt;
    private javax.swing.JLabel txt2;
    private javax.swing.JDialog 도서_관리;
    private javax.swing.JDialog 도서_반납;
    private javax.swing.JDialog 도서_일반;
    private javax.swing.JDialog 도서삭제_확인;
    private javax.swing.JDialog 도서수정;
    private javax.swing.JDialog 도서추가;
    private javax.swing.JDialog 로그인_실패;
    private javax.swing.JDialog 회원가입;
    private javax.swing.JDialog 회원가입_완료;
    // End of variables declaration//GEN-END:variables
}
